#!/bin/bash

export PERL5LIB=/home/mchamber/circos-brain/deps/lib/perl5/site_perl/5.8.8/:/home/mchamber/circos-brain/deps/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi/

MAP=$1
LINKS=$2
OUT=$3
PERL=`which perl`

if [ $# -ne 3 ]; then 
	echo "Error: Usage:"
	echo "run map links outdir"
	exit -1
fi

mkdir $OUT

cp -a etc $OUT/
mkdir $OUT/data

DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$PERL $DIR/parsemap -map $1 -links $2 -datadir $OUT/data
cd $OUT
$PERL $DIR/circos-0.62-1/bin/circos 
